### ISSUE TITLE
upm -f -s .old does not delete .old file

### ISSUE THREAD

**Issue by Konfekt** [uxcn/sh-helpers#1]
First `cpm -f -s .old foo`, then `upm  -f -s .old foo`. Expected: nothing changed. Found: a new file `foo.old` exists.

**Comment by uxcn** [comment]
`upm` actually expects the whole filename as an argument instead of just the base.  It's supposed to allow it to distinguish between more than one `pm` or `cpm` file.

For example, if you had `foo`, `foo.old`, and `foo.old.old`.  Running `upm -f -s .old foo` could mean `foo.old.old -> foo.old` or `foo.old -> foo` or `foo.old.old -> foo.old, foo.old -> foo`.  The same thing would be true for `pm` and `cpm`.

You can still pass files using globs though.  So instead of `upm -f -s .old foo.old` you could do `upm -f -s .old foo*`.  If there are multiple files, it only shifts one suffix unless you pass `-a` (e.g. `foo.old.old -> foo.old`).

Let me know if that fixes the issue for you.

**Comment by Konfekt** [comment]
Ok. Indeed `upm foo.old` was also tried, but did not work. Now it does. Fine with me. Thanks!

**Comment by uxcn** [comment]
You might want to upgrade the version if you're on anything earlier than 0.1.3; there were some bugs.

Otherwise if you still have any problems, just let me know.
